name: whipp-standard

channels:
  - conda-forge

dependencies:
  # Core Python stuff
  - python==3.8.11
  - pip==21.2.4

  # General scientific packages
  - numpy==1.21.0
  - pandas==1.3.2

  # Plotting
  - matplotlib==3.4.3

  # Jupyter environment
  - jupyterlab==3.1.7
  - notebook==6.4.3
  - ipython==7.26.0
  - nbgrader
